config/urls.py
from django.contrib import admin
from django.urls import path,include
from config.settings.development import DEBUG,STATIC_URL,STATIC_ROOT,MEDIA_ROOT,MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
  
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import (index,
technician_service_computer_repair,
technician_service_desktop_remapair,
technician_service_mobile_repair,
technician_service_tablets_remapair,
technician_service_television_remapair,ItemDetail,comments,contact_us)

app_name = 'mainapp'


urlpatterns = [
    path('',index, name = "index_page"),
    path('mobilepair/',technician_service_mobile_repair,name = "mobilerepair"),
    path('desktoprepair/',technician_service_desktop_remapair,name = "desktoprepair"),
    path('tabletrepair/',technician_service_tablets_remapair,name = "tabletrepair"),
    path('televisionrepair/',technician_service_television_remapair,name = "televisonrepair"),
    path('computerrepair/',technician_service_computer_repair, name = "computerrepair"),
    path('technician/<slug>/', ItemDetail.as_view(), name='techniciandetail'),
    path('comments/', comments, name='comments'),
    path('contact/', contact_us, name='contact'),
    
   
]

mainapp/models.py
from django.db import models
from django.db.models.query import ModelIterable
from django.db import models
import random
import os
from django.db.models import Q
from datetime import datetime
from django.utils.timezone import now
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from mainapp.utils import unique_slug_generator,category_unique_slug_generator
import uuid

# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "products/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


def upload_image_technician(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "technician/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


class Banner(models.Model):
    banner_picture = models.FileField(upload_to = upload_image_path ,null=True,blank=False)
    banner_description = models.CharField(max_length=200,blank =True , null= True)

    def __str__(self):
        return self.banner_description


class TechnicianDetails(models.Model):
    technician_name  = models.CharField(max_length=100)
    email = models.EmailField()
    technician_picture = models.FileField(upload_to = upload_image_technician ,null=True,blank=False)
    technician_overview = models.TextField()
    shop_location = models.CharField(max_length=150, blank=True,null=True)
    phone_number = models.CharField(max_length=150, blank=True,null=True)
    email = models.CharField(max_length=150, blank=True,null=True)
    facebook_url = models.CharField(max_length=150, blank=True,null=True)
    twitter_url = models.CharField(max_length=150, blank=True,null=True)
    youtube_url = models.CharField(max_length=150, blank=True,null=True)
    vimeo_url = models.CharField(max_length=150, blank=True,null=True)
    slug = models.SlugField(blank=True,unique=True,default=uuid.uuid4)

    def __str__(self):
        return self.technician_name

    def get_absolute_url(self):
        return reverse("mainapp:techniciandetail", kwargs={
            'slug': self.slug
        })
def product_presave_reciver(sender, instance, *args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_presave_reciver,sender = TechnicianDetails)   


class Services(models.Model):
    CHOICES = (
        ('MR', 'Mobile Repair'),
        ('CR', 'Computer Repair'),
        ('TR', 'Television Repair'),
        ('DR', 'Desktop Repair'),
        ('TBR', 'Tablet Repair'),
    )
    technician =  models.ForeignKey(TechnicianDetails,on_delete= models.CASCADE)
    technician_services = models.CharField(max_length=300, choices = CHOICES)

    def __str__(self):
        return self.technician_services
    

class Testimonies(models.Model):
    technician  = models.ForeignKey(TechnicianDetails,on_delete= models.CASCADE)
    Clients_Name = models.CharField(max_length=150)
    comment  =  models.TextField()
    date = models.DateTimeField(default=now, editable=False)

    def __str__(self):
        return self.Clients_Name
    
    

mainapp/forms.py
from django import forms
from .models import Testimonies


class CommentForm(forms.ModelForm):
    class Meta:
        model = Testimonies
        fields = ['Clients_Name','comment']
        widgets = {
            'Clients_Name':forms.TextInput(
                attrs = {
                      "type":"text", "placeholder":"Name*", "required" : "",'placeholder' : "full name"
                }
            ),
            'comment':forms.Textarea(
                attrs = {
                     "rows":"6" , "placeholder":"Message",'placeholder': " comments"
                }
            )
        }

mainapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
import datetime
from .models import Banner
from .models import TechnicianDetails,Services,Testimonies
from django.views.generic import DetailView,View,ListView
from .forms import  CommentForm

# Create your views here.

def index(request):
    banners = Banner.objects.all()
    technicians =  TechnicianDetails.objects.all()

    context = {
        'banner' : banners,
        'technician' : technicians
    }
    
    return render(request,'homepage/index.html',context)


def technician_service_mobile_repair(request):
    tagname = 'MR'
    services = Services.objects.filter(technician_services__iexact = tagname)
    
    
    context = {
        'services' : services,
        'tagname' : tagname
    }
    return render(request,'technicians/index.html',context)

def technician_service_computer_repair(request):
    
    tagname = 'CR'
    services = Services.objects.filter(technician_services__iexact = tagname)
    
    
    context = {
        'services' : services,
        'tagname' : tagname
    }
    return render(request,'technicians/index.html',context)

def technician_service_desktop_remapair(request):
    tagname = 'DR'
    services = Services.objects.filter(technician_services__iexact = tagname)
    
    
    context = {
        'services' : services,
        'tagname' : tagname
    }
    return render(request,'technicians/index.html',context)

def technician_service_tablets_remapair(request):
    tagname = 'TBR'
    services = Services.objects.filter(technician_services__iexact = tagname)
    
    
    context = {
        'services' : services,
        'tagname' : tagname
    }
    return render(request,'technicians/index.html',context)

def technician_service_television_remapair(request):
    tagname = 'TR'
    services = Services.objects.filter(technician_services__iexact = tagname)
    
    
    context = {
        'services' : services,
        'tagname' : tagname
    }
    return render(request,'technicians/index.html',context)



class ItemDetail(DetailView):
    model = TechnicianDetails
    template_name = "detailedview/index.html"
    def get_context_data(self, **kwargs):
        services = Services.objects.all()
        testimonies = Testimonies.objects.all()
        form  = CommentForm()
        context = super().get_context_data(**kwargs)
        context["services"] = services
        context["testimonies"] = testimonies
        context["form"] = form
        return context

def comments(request):
    comment_id = request.POST.get("product_id")
    form = CommentForm(request.POST or None)
    if form.is_valid:
        instance = form.save(commit=False)
        technician = TechnicianDetails.objects.get(id=comment_id)
        instance.technician = technician
        instance.save()
    
    return redirect("/")


def contact_us(request):
    return render(request,'contact_us.html',{})

mainapp/templates/contact_us.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!--Page Title-->
 <section class="page-title" style="background-image:url(images/breadcrumb-bg.jpg)">
    <div class="container">
        <div class="clearfix">
            <div class="float-left">
                <div class="title">Welcome to Repairzone</div>
                <h2>Contact Us</h2>
            </div>
            <div class="float-right">
                <ul class="page-breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li>Contact Us</li>
                </ul>
            </div>
        </div>
    </div>
</section>


<section class="contact-page-section inner-wrapper">
  <div class="container">
    <div class="row clearfix"> 
        <!-- Info Column -->
        <div class="info-column col-lg-5 col-md-12 col-sm-12">
          <div class="inner-column">
            <div class="sec-title">
              <div class="title">Get in Touch</div>
              <h2>For Any Kind of Help <br>
                And Informations</h2>
              <div class="text">We’re glad to discuss your organisation’s situation. <br>
                So please contact us via the details below, or enter your request.</div>
            </div>
            <ul class="list-style-two style-two">
              <li> <span class="icon fa fa-map"></span> <strong>Head Office Address:</strong> Upper Hill road </li>
              <li> <span class="icon fa fa-phone"></span> <strong>Call for help:</strong> (254) 704157038 </li>
              <li> <span class="icon far fa-envelope"></span> <strong>Mail us for information</strong> info@test.com,   test@test.com </li>
            </ul>
          </div>
        </div>
        
        <!-- Form Column -->
       
      </div>
      
  </div>
</section>
{% endblock content %}

mainapp/templates/detailedview/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

 <section class="page-title" style="background-image:url({% static 'images/breadcrumb-bg.jpg' %})">
    <div class="container">
        <div class="clearfix">
            <div class="float-left">
                <div class="title">Welcome to Repairzone</div>
                <h2>{{object.technician_name}}</h2>
            </div>
            <div class="float-right">
                <ul class="page-breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li>{{object.technician_name}}</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!--End Page Title-->
<!-- About Sec Start -->
<section class="blog-area blog-sec inner-wrapper">
  <div class="container">
    <div class="row">
        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">
          <div class="blog-details"> <img src="{{object.technician_picture.url}}" alt="">
            <h2>Overview</h2>
            <p>{{object.technician_overview}}</p>
          </div>
          <div class="post-share-and-tag row">
            <div class="col-xl-7 col-lg-7 col-md-6">
              
            </div>
            <div class="col-xl-5 col-lg-5 col-md-6">
              <div class="social"> 
              {% if object.facebook_url %}
              <a href="{{object.facebook_url}}" class="cl-facebook"><i class="fab fa-facebook-f"></i></a> 
              {% endif %}
              
              {% if object.twitter_url %}
              <a href="{{object.twitter_url}}" class="cl-twitter"><i class="fab fa-twitter"></i></a> 
              {% endif %}

              {% if object.youtube_url %}
              <a href="{{object.youtube_url }}" class="cl-youtube"><i class="fab fa-youtube"></i></a> 
              {% endif %}
              
              
              </div>
            </div>
          </div>
          <h3>Comments</h3>
          {% if testimonies %}
            {% for t in testimonies %}
            {% if t.technician.id == object.id %}
      
          <div class="blog-all-comments">
            
            
            <div class="blog-comments">
              <div class="author-thumb"> <img src="{% static 'images/author-1.jpg' %}" alt="" /> </div>
              <div class="author-comments">
                <div class="author-details">
                  <h4>{{t.Clients_Name}}</h4>
                  
                </div>
                <div class="author-designation"> {{t.date}} </div>
                <p>{{t.comment}}</p>
              </div>
            </div>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            
          
        
          <div class="blog-comment-form">
            <h3>Leave a Comment</h3>
          <form method ='POST' action = '{% url "mainapp:comments" %}' class="form">
          {% csrf_token %}
          <input type="hidden" name="product_id" value="{{object.id}}"/>
              <div class="row">
                <div class="col-md-6">
                  {{form.Clients_Name}}
                </div>
                <div class="col-md-12">
                  {{form.comment}}
                </div>
                <div class="col-md-12">
                  <button type="submit" class="default-btn">Post Comment</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6">
          <div class="site-sidebar">
            <div class="single-sidebar">
             
            </div>
            <div class="single-sidebar">
              <h3>Services</h3>
              <ul>
                {% if services %}
                {% for s in  services %}
                {% if s.technician.id  ==  object.id %}
                <li><a href="javascript:void(0)">{{s.get_technician_services_display}}</a></li>
                {% endif %}
                {% endfor %}
                {% endif %}
              </ul>
            </div>
           



            {% if object.phone_number or object.email %}
           <div class="sidebar-widget contact-widget">
                <div class="widget-content" style="background-image:url(images/background-pattern.png)">
                  <div class="icon flaticon-phone-call"></div>
                  <div class="text">Need His service? <br>
                    Contact him on</div>
                    {% if object.phone_number %}
                  <div class="number">{{object.phone_number}}</div>
                  {% endif %}
                  {% if  object.email %}
                  <div class="email">{{object.email}}</div>
                  {% endif %}
                </div>
              </div>
            {% endif %}


       
          </div>
        </div>             
  </div>
</section>
{% endblock content %}

mainapp/templates/homepage/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ttm-stickable-header-w end--> 
<!-- Site Slider Start -->
<section class="slider-one">
  <div class="slider-one__carousel owl-carousel owl-theme">
    {% if banner %}
    {% for p in banner  %}
    <div class="item slider-one__slider-1" style="background-image: url({{p.banner_picture.url}});">
      <div class="container">
        <h2 class="slider-one__title">Repair your Computer <br>
          laptop & iphone. </h2>
        <!-- /.slider-one__title -->
        <p class="slider-one__text">{{p.banner_description}}</p>
        <a href="{% url 'mainapp:contact' %}" class="default-btn slider-one__text">Contact Us <i class="fas fa-long-arrow-alt-right"></i> </a> 
        <!-- /.slider-one__text --> 
      </div>
      <!-- /.container --> 
    </div>
    {% endfor %}
    {% endif %}
    <!-- /.item -->
   
    <!-- /.item -->
    
    <!-- /.item --> 
  </div>
  <!-- /.slider-one__carousel --> 
</section>
<!-- Features Sec Start -->
<section class="features-sec mt-minus-70 pt-0 pb-70">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-sm-6 p-0">
        <div class="single-offer"> <i class="icon mbri-mobile"></i>
          <h3>Mobile Service</h3>
          <p>This includes mobile screen repair, motherbord replacement , button repair etc</p>
          <a class="circle-read-more" href="{% url "mainapp:mobilerepair" %}"> <i class="ti-angle-right"></i> </a> </div>
      </div>
      <div class="col-lg-3 col-sm-6 p-0">
        <div class="single-offer"> <i class="icon mbri-laptop"></i>
          <h3>Computer Service</h3>
          <p>This includes computer screen repair, motherbord replacement , button repair etc</p>
          <a class="circle-read-more" href="{% url "mainapp:computerrepair" %}"> <i class="ti-angle-right"></i> </a> </div>
      </div>
      <div class="col-lg-3 col-sm-6 p-0">
        <div class="single-offer"> <i class="icon mbri-desktop"></i>
          <h3>Television Service</h3>
          <p>This includes Television screen repair, motherbord replacement , button repair etc</p>
          <a class="circle-read-more" href="{% url "mainapp:televisonrepair" %}"> <i class="ti-angle-right"></i> </a> </div>
      </div>
      <div class="col-lg-3 col-sm-6 p-0">
        <div class="single-offer"> <i class="icon mbri-responsive"></i>
          <h3>Desktop Service</h3>
          <p>This includes Desktop screen repair, motherbord replacement , button repair etc</p>
          <a class="circle-read-more" href="{% url "mainapp:desktoprepair" %}"> <i class="ti-angle-right"></i> </a> </div>
      </div>
    </div>
  </div>
</section>
<!-- About Sec Start -->
<section class="about-sec">
  <div class="container">
    <div class="section-title"> <span>What We Do </span>
      <h2>About Us</h2>
    </div>
    <div class="row justify-content-between align-items-center">
      <div class="col-md-12 col-lg-5">
        <div class="video-promo-content mb-md-4 mb-lg-0">
          <h2>Service We Offers</h2>
       
          <ul class="list-unstyled tech-feature-list">
            <li class="py-1"><span class="ti-check-box mr-2"></span><strong>Mobile Repair</strong> Services </li>
            <li class="py-1"><span class="ti-check-box mr-2"></span><strong>Computer Repair</strong> Service</li>
            <li class="py-1"><span class="ti-check-box mr-2"></span><strong>Television Repair</strong> Services</li>
            <li class="py-1"><span class="ti-check-box mr-2"></span><strong>Desktop Repair</strong> Services</li>
            <li class="py-1"><span class="ti-check-box mr-2"></span><strong>Tab Repair</strong> Services</li>
          </ul>
        </div>
      </div>
      <div class="col-md-12 col-lg-6 mt-3 mt-lg-0">
        <div class="card border-0 shadow-sm text-white"> <img src="{% static 'images/about-img.jpg' %}" alt="video" class="img-fluid rounded shadow-sm" data-popupalt-original-title="null" title="video">
          <div class="card-img-overlay text-center" data-popupalt-original-title="null" title="video"> <a href="../watch.html?v=9No-FiEInLA" class="popup-youtube video-play-icon color-bip shadow"><span class="ti-control-play" data-popupalt-original-title="null" title="null"></span> </a> </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Services Sec Start -->
<section class="services-sec service-area-two">
  <div class="container">
    <div class="section-title"> <span>What We Do </span>
      <h2>Services</h2>
    </div>
    <div class="row">
      <div class="col-lg-4 col-sm-6"> 
        <!-- Single Services Start -->
        <div class="single-service">
          <div class="service-content-wrap"> <i class="icon mbri-mobile"></i>
            <h3>Mobile Repair</h3>
            <p>This includes mobile screen repair, motherbord replacement , button repair etc</p>
          </div>
          <div class="service-heading"> <a class="circle-read-more" href="{% url "mainapp:mobilerepair" %}">
            <h3>Mobile Repair</h3>
            <i class="ti ti-angle-right"></i> </a> </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6"> 
        <!-- Single Services Start -->
        <div class="single-service">
          <div class="service-content-wrap"> <i class="icon mbri-laptop"></i>
            <h3>Computer Repair</h3>
            <p>This includes computer screen repair, motherbord replacement , button repair etc</p>
          </div>
          <div class="service-heading"> <a class="circle-read-more" href="{% url "mainapp:computerrepair" %}">
            <h3>Computer Repair</h3>
            <i class="ti ti-angle-right"></i> </a> </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6"> 
        <!-- Single Services Start -->
        <div class="single-service">
          <div class="service-content-wrap"> <i class="icon mbri-desktop"></i>
            <h3>Television Repair</h3>
            <p>This includes Television screen repair, motherbord replacement , button repair etc</p>
          </div>
          <div class="service-heading"> <a class="circle-read-more" href="{% url "mainapp:televisonrepair" %}">
            <h3>Television Repair</h3>
            <i class="ti ti-angle-right"></i> </a> </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6"> 
        <!-- Single Services Start -->
        <div class="single-service">
          <div class="service-content-wrap"> <i class="icon mbri-responsive"></i>
            <h3>Desktop Repair</h3>
            <p>This includes Desktop screen repair, motherbord replacement , button repair etc</p>
          </div>
          <div class="service-heading"> <a class="circle-read-more" href="{% url "mainapp:desktoprepair" %}">
            <h3>Desktop Repair</h3>
            <i class="ti ti-angle-right"></i> </a> </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6"> 
        <!-- Single Services Start -->
        <div class="single-service">
          <div class="service-content-wrap"> <i class="icon mbri-tablet"></i>
            <h3>Tablet Repair</h3>
            <p>This includes Tablet screen repair, motherbord replacement , button repair etc</p>
          </div>
          <div class="service-heading"> <a class="circle-read-more" href="{% url "mainapp:tabletrepair" %}">
            <h3>Tablet Repair</h3>
            <i class="ti ti-angle-right"></i> </a> </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6"> 
        <!-- Single Services Start -->
        <div class="single-service">
          <div class="service-content-wrap"> <i class="icon mbri-like"></i>
            <h3>Quality Support</h3>
            <p>We offer Quality support which is timely, when you contact us via email or phone</p>
          </div>
          <div class="service-heading"> <a class="circle-read-more" href="service-details.html">
            <h3>Quality Support</h3>
            <i class="ti ti-angle-right"></i> </a> </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Our Team Sec Start -->
<section class="our-team-sec">
  <div class="container">
    <div class="section-title"> <span>Professional Team </span>
      <h2>Our Techincal Team</h2>
    </div>
    <div class="row">
    {% if technician %}
    {% for t in technician %}
      <div class="col-lg-3 col-sm-6"> 
        <!-- Single Team Start -->
        <div class="single-team"> <img src="{{t.technician_picture.url}}" alt="" data-popupalt-original-title="null" title="">
          <div class="team-content">
            <h3>{{t.technician_name}}</h3>
            <span>{{t.shop_location}}</span> </div>
          <ul>
          {% if t.facebook_url %}
            <li> <a href="#"><i class="fab fa-facebook-f"></i></a> </li>
          {% elif t.twitter_url %}
            <li> <a href="#"><i class="fab fa-twitter"></i></a> </li>
          {% elif t.vimeo_url %}
        
            <li> <a href="#"><i class="fab fa-vimeo-v"></i></a> </li>
          {% else %}

          {% endif %}
          </ul>
        </div>
      </div>
    {% endfor %}
    {% endif %}
     
    </div>
  </div>
</section>

<!-- Testimonials Section -->

<!-- Blog Section -->
{% endblock content %}

mainapp/templates/technicians/index.html
{% extends 'base.html' %}


{% block content %}

 <section class="page-title" style="background-image:url(images/breadcrumb-bg.jpg)">
    <div class="container">
        <div class="clearfix">
            <div class="float-left">
                <div class="title">Welcome to Repairzone</div>
                 {% if tagname %}
                {% if tagname  == 'MR' %}
                <h2>Mobile  Repair</h2>
                {% elif tagname  == 'CR' %}
                <h2>Computer  Repair</h2>
                {% elif tagname  == 'TR' %}
                <h2>Television  Repair</h2>
                {% elif tagname  == 'DR' %}
                <h2>Desktop  Repair</h2>
                {% elif tagname  == 'TBR' %}
                <h2>Tablet  Repair</h2>
                {% else %}
                {% endif %}
                {% endif %}
            </div>
            <div class="float-right">
                <ul class="page-breadcrumb">
                    <li><a href="index.html">Home</a></li>
                     {% if tagname %}
                    {% if tagname  == 'MR' %}
                    <li>Mobile  Repair</li>
                    {% elif tagname  == 'CR' %}
                    <li>Computer  Repair</li>
                    {% elif tagname  == 'TR' %}
                    <li>Television  Repair</li>
                    {% elif tagname  == 'DR' %}
                    <li>Desktop  Repair</li>
                    {% elif tagname  == 'TBR' %}
                    <li>Tablet  Repair</li>
                    {% else %}
                    {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</section>
<!--End Page Title-->
<!-- About Sec Start -->


<!-- Blog Section -->
<section class="blog-sec">
<div class="container">
    <!-- Sec Title -->
    <div class="section-title"> 
    {% if tagname %}
    {% if tagname  == 'MR' %}
	  <span>Mobile  Repair</span>
    {% elif tagname  == 'CR' %}
    <span>Computer  Repair</span>
    {% elif tagname  == 'TR' %}
    <span>Television  Repair</span>
    {% elif tagname  == 'DR' %}
    <span>Desktop  Repair</span>
    {% elif tagname  == 'TBR' %}
    <span>Tablet  Repair</span>
    {% else %}
    {% endif %}
    {% endif %}
      <h2>Our Technicians</h2>
    </div>
<div class="row">


<!-- Single Blog Sec -->
{% if services %}

{% for sv in services %}

<div class="col-lg-4 col-md-6">
    <div class="single-blog"> <a href="{{sv.technician.get_absolute_url}}"> <img src="{{sv.technician.technician_picture.url}}" alt=""> </a>
        <div class="blog-content"> <a class="user" href="#"> <i class="bx bx-user"></i></a>
            <h3> <a href="{{sv.technician.get_absolute_url}}">{{sv.technician.technician_name}}</a> </h3>
            <ul>
            <li>{{sv.technician.shop_location}}<i class="bx bx-calendar"></i> </li>
            <li class="date"> <a class="read-more" href="{{sv.technician.get_absolute_url}}"> View More <i class="fas fa-arrow-right bx-fade-right"></i> </a> </li>
            </ul>
        </div>
    </div>
 </div>

{% endfor %}
{% endif %}




 
 </div>	
</div>
</section>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>
{% include 'preloader.html' %}
{% include 'header.html' %}

{% block content %}
{% endblock content %}

{% include 'footer.html' %}
{% include 'scripts.html' %}
</body>

</html>

templates/head.html
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>Repairzone - Computer & Mobile Repair HTML5</title>
<!-- Plugins CSS -->
<link href="{% static 'css/plugins.css' %}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<!-- Favicon -->
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

templates/header.html
{% load static %}
<header class="site-header site-header__header-one site-header__home-one ">
  <nav class="navbar navbar-expand-lg navbar-light header-navigation stricky">
    <div class="container clearfix"> 
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="logo-box"> <a class="navbar-brand" href="/"> <img src="{% static 'images/logo.png' %}" width="185" class="main-logo" alt="Awesome Image"> </a>
        <button class="menu-toggler" data-target=".main-navigation"> <span class="fa fa-bars"></span> </button>
      </div>
      <!-- /.logo-box --> 
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="main-navigation">
        <ul class="navigation-box @@extra_class">
          <li class="current"><a href="/">Home</a></li>
         
        </ul>
      </div>
      <!-- /.navbar-collapse -->
     
      <!-- /.right-side-box --> 
    </div>
    <!-- /.container --> 
  </nav>
</header>